WORKFLOW_TEMPLATES = {
    "scene_to_panels": {
        "name": "Scene → Panels",
        "description": "Gather scene context, compose image prompts, and generate storyboard panels",
        "category": "production",
        "steps": [
            {"id": "gather", "step_type": "gather_buckets", "label": "Gather Scene Context",
             "config": {"container_types": ["character", "scene", "location"], "max_items": 10},
             "position": {"x": 100, "y": 200}},
            {"id": "prompt", "step_type": "prompt_template", "label": "Compose Panel Prompts",
             "config": {"template": "Based on this scene context:\n\n{{context}}\n\nGenerate detailed panel descriptions for a manga/webtoon scene. Include camera angles, character positions, and visual mood."},
             "position": {"x": 400, "y": 200}},
            {"id": "review", "step_type": "review_prompt", "label": "Review Prompts",
             "config": {},
             "position": {"x": 700, "y": 200}},
            {"id": "generate", "step_type": "llm_generate", "label": "Generate Panel Descriptions",
             "config": {"model": "", "temperature": 0.8, "max_tokens": 4096},
             "position": {"x": 1000, "y": 200}},
            {"id": "save", "step_type": "save_to_bucket", "label": "Save Panels",
             "config": {"container_type": "panel"},
             "position": {"x": 1300, "y": 200}},
        ],
        "edges": [
            {"source": "gather", "target": "prompt"},
            {"source": "prompt", "target": "review"},
            {"source": "review", "target": "generate"},
            {"source": "generate", "target": "save"},
        ]
    },
    "concept_to_outline": {
        "name": "Concept → Outline",
        "description": "Brainstorm ideas from a concept, then architect a structured story outline",
        "category": "writing",
        "steps": [
            {"id": "input", "step_type": "review_prompt", "label": "Enter Your Concept",
             "config": {},
             "position": {"x": 100, "y": 200}},
            {"id": "brainstorm", "step_type": "llm_generate", "label": "Brainstorm Ideas",
             "config": {"model": "", "temperature": 1.0, "max_tokens": 2048},
             "position": {"x": 400, "y": 200}},
            {"id": "review_ideas", "step_type": "review_prompt", "label": "Review Ideas",
             "config": {},
             "position": {"x": 700, "y": 200}},
            {"id": "architect", "step_type": "llm_generate", "label": "Build Story Outline",
             "config": {"model": "", "temperature": 0.7, "max_tokens": 4096},
             "position": {"x": 1000, "y": 200}},
            {"id": "approve", "step_type": "approve_output", "label": "Approve Outline",
             "config": {},
             "position": {"x": 1300, "y": 200}},
            {"id": "save", "step_type": "save_to_bucket", "label": "Save Outline",
             "config": {"container_type": "outline"},
             "position": {"x": 1600, "y": 200}},
        ],
        "edges": [
            {"source": "input", "target": "brainstorm"},
            {"source": "brainstorm", "target": "review_ideas"},
            {"source": "review_ideas", "target": "architect"},
            {"source": "architect", "target": "approve"},
            {"source": "approve", "target": "save"},
        ]
    },
    "outline_to_draft": {
        "name": "Outline → Draft",
        "description": "Gather context from outline and characters, generate prose draft, extract entities",
        "category": "writing",
        "steps": [
            {"id": "gather", "step_type": "gather_buckets", "label": "Gather Story Context",
             "config": {"container_types": ["character", "scene", "outline", "location"], "max_items": 15},
             "position": {"x": 100, "y": 200}},
            {"id": "prompt", "step_type": "prompt_template", "label": "Compose Writing Prompt",
             "config": {"template": "You are a skilled prose writer. Using the following story context:\n\n{{context}}\n\nWrite a vivid, engaging scene draft. Focus on:\n- Show don't tell\n- Character voice consistency\n- Sensory details\n- Natural dialogue"},
             "position": {"x": 400, "y": 200}},
            {"id": "review", "step_type": "review_prompt", "label": "Review Writing Prompt",
             "config": {},
             "position": {"x": 700, "y": 200}},
            {"id": "draft", "step_type": "llm_generate", "label": "Generate Draft",
             "config": {"model": "", "temperature": 0.85, "max_tokens": 8192},
             "position": {"x": 1000, "y": 200}},
            {"id": "save", "step_type": "save_to_bucket", "label": "Save Fragment",
             "config": {"container_type": "fragment"},
             "position": {"x": 1300, "y": 200}},
        ],
        "edges": [
            {"source": "gather", "target": "prompt"},
            {"source": "prompt", "target": "review"},
            {"source": "review", "target": "draft"},
            {"source": "draft", "target": "save"},
        ]
    },
    "topic_to_research": {
        "name": "Topic → Research",
        "description": "Deep-dive into a real-world topic and save structured findings to the Research Library",
        "category": "research",
        "steps": [
            {"id": "input", "step_type": "review_prompt", "label": "Enter Research Topic",
             "config": {},
             "position": {"x": 100, "y": 200}},
            {"id": "research", "step_type": "research_deep_dive", "label": "Research Deep Dive",
             "config": {},
             "position": {"x": 400, "y": 200}},
            {"id": "review", "step_type": "approve_output", "label": "Review Findings",
             "config": {},
             "position": {"x": 700, "y": 200}},
            {"id": "save", "step_type": "save_to_bucket", "label": "Save to Library",
             "config": {"container_type": "research_topic"},
             "position": {"x": 1000, "y": 200}},
        ],
        "edges": [
            {"source": "input", "target": "research"},
            {"source": "research", "target": "review"},
            {"source": "review", "target": "save"},
        ]
    },
    "draft_to_polish": {
        "name": "Draft → Polish",
        "description": "Review draft for style consistency, check continuity, and produce final edit",
        "category": "quality",
        "steps": [
            {"id": "gather", "step_type": "gather_buckets", "label": "Gather Draft + Style Guide",
             "config": {"container_types": ["fragment", "character"], "max_items": 10},
             "position": {"x": 100, "y": 200}},
            {"id": "style_check", "step_type": "llm_generate", "label": "Style & Voice Check",
             "config": {"model": "", "temperature": 0.3, "max_tokens": 4096},
             "position": {"x": 400, "y": 200}},
            {"id": "review_style", "step_type": "review_prompt", "label": "Review Style Notes",
             "config": {},
             "position": {"x": 700, "y": 200}},
            {"id": "final_edit", "step_type": "llm_generate", "label": "Final Polish",
             "config": {"model": "", "temperature": 0.5, "max_tokens": 8192},
             "position": {"x": 1000, "y": 200}},
            {"id": "approve", "step_type": "approve_output", "label": "Approve Final",
             "config": {},
             "position": {"x": 1300, "y": 200}},
            {"id": "save", "step_type": "save_to_bucket", "label": "Save Polished Draft",
             "config": {"container_type": "fragment"},
             "position": {"x": 1600, "y": 200}},
        ],
        "edges": [
            {"source": "gather", "target": "style_check"},
            {"source": "style_check", "target": "review_style"},
            {"source": "review_style", "target": "final_edit"},
            {"source": "final_edit", "target": "approve"},
            {"source": "approve", "target": "save"},
        ]
    }
}
